### ISSUE TITLE
Monk Class

### ISSUE THREAD

**Issue by ZerraxTM** [holydeew/WoWHellgarve-Legion#214]
Bug Report - Monk Class: "Crackling Jade Lightning" and "Storm, Earth and Fire" abilities

Date : May 17, 2023

Bug Description:
It has been found that the combination of the "Crackling Jade Lightning" and "Storm, Earth, and Fire" spells of the Monk class allows for one-shot attacks on any player and raid boss, regardless of whether they are equipped with a Flexcraft or not. This bug has a significant impact on the balance of the game, as it allows a Monk player to cause excessive damage without the ability to retaliate from other players.

Steps to reproduce the bug:

    Select a Monk character and make sure they are high enough level to have access to the "Crackling Jade Lightning" and "Storm, Earth, and Fire" spells.
    Engage in combat with another player, either in Player vs. Player (PvP) or Player vs. Environment (PvE) mode.
    Use the spell "Storm, Earth and Fire" to create clones of your character.
    Then use the "Crackling Jade Lightning" spell on the chosen target.

Expected result:
When the "Crackling Jade Lightning" spell is used in conjunction with "Storm, Earth, and Fire", the damage dealt to the target should be balanced and within the game specifications. The target should take normal damage and have the ability to defend or retaliate.

Observed Result:
When the "Crackling Jade Lightning" spell is used after activating "Storm, Earth, and Fire", the damage dealt to the target is excessively high and more importantly displays as negative and can cause a one shot, eliminating the target instantly, whether it is a player or a boss.

Bug Impact:
This bug has a significant impact on the gameplay experience of other players, as it makes the Monk class extremely powerful and virtually invincible when using this spell combination. Opposing players cannot react or defend effectively against these one-shot attacks, disrupting the balance of the game in PvP and PvE.

Bug Reproduction:
The bug has been successfully reproduced several times by different players in different game environments (PvP and PvE). The excessive damage caused by the combination of the "Crackling Jade Lightning" and "Storm, Earth, and Fire" spells is consistent and does not appear to be related to any specific conditions.

SPELL ID(s) : 137639 ; 117952

Player who helped me : Guery

**Comment by Gueryghembal** [comment]
Precision : The simple combination of "Crackling Jade Lightning" and "Storm, Earth and Fire" **is not enough.**

You need to do it correctly, to use **2 charges of "Storm, Earth and Fire"**, and for easily reproduction, **use a macro** where you put "/cast Storm, Earth and Fire" twice.

Also, the damage do not really matter, the problem is that your damage are negative because using 2 charges of this spell literaly divide your damage by 3³, and so, can oneshot everything, if thoses things have not over _±5000M HP_. And depend if it's a boss with phases or not.

It's important to note that the damage come from you **and sometimes** from the spirits too.

**Comment by skeezerbean** [comment]
Fixed
