### ISSUE TITLE
[NPC] [Demon Hunter Class Hall] Seer Aleis.

### ISSUE THREAD

**Issue by Novrainn** [holydeew/WoWHellgarve-Legion#272]
**How it normally works** : An NPC is supposed to be in the lower level of Mardum, the Shattered Abyss, once we have completed level 5 with Loramus Thalipedes "Concentrated War Effort" to order one Broken Seal of Fate per week for FREE .

**What is the problem** : Despite having completed the level in question, the NPC does not appear, and is not present on the PTR as well.

**Comment by skeezerbean** [comment]
Can you give me some more details on this? - I assume this is the NPC - https://www.wowhead.com/npc=112992/seer-aleis#comments

**Comment by Novrainn** [comment]
Yep, its him.

Normally, this npc is supposed to be in the class hall once you have unlocked the class hall improvement talent (see screenshot below) Except that it does not appear (it is a friend who unlocked it, me not, and he confirms to me that it does not appear).
When I was on the PTR in GM on, it wasn't there either, I accidentally added it xd.
![WoWScrnShot_072023_234330](https://github.com/holydeew/WoWHellgarve-Legion/assets/133527332/b3ac8188-f93b-4e76-b5b5-2cc443032174)

**Comment by skeezerbean** [comment]
So I'm testing, and can add this NPC phased based on whether you learn that talent or not. And he gives a quest to place a work order, but no idea how to actually place it. From the quest details for this NPC it sounds like there should be a gossip option, but the option doesn't show. The settings in DB are correct, no conditions restricting. I'm guessing because of the type of option there's something internal that determines whether it shows, and how it handles it. There's nothing scripted for this NPC, or 1 other which I found the same option, so not sure whether that part works. If not, then likely it won't be fixed any time soon and would need source changes.

I'll send in the fix for what I have at least.
