### ISSUE TITLE
[Quest] [NPC] [Legion] A Walk with the Spirits and The Skyhorn Tribe

### ISSUE THREAD

**Issue by justSelim** [holydeew/WoWHellgarve-Legion#328]
Quest ID: [A Walk with the Spirits 40515](https://www.wowhead.com/quest=40515/a-walk-with-the-spirits) 
[The Skyhorn Tribe 38913](https://www.wowhead.com/quest=38913/the-skyhorn-tribe)

NPC ID: [Mayla Highmountain 93826](https://www.wowhead.com/npc=93826/mayla-highmountain)

Current Behaviour: Quests are not available but should be available after completing Quest [Get to High Ground 38909](https://www.wowhead.com/quest=38909/get-to-high-ground) and accepting Quest ( not completing!!!! ) [The Bloodtotem Tribe 38912](https://www.wowhead.com/quest=38912/the-bloodtotem-tribe)

Expected Behaviour: Quest should be available after completing the Quest [Get to High Ground 38909](https://www.wowhead.com/quest=38909/get-to-high-ground)

**Comment by skeezerbean** [comment]
Quest was set to require Q39579 Back Door, fix sent in to now set to 38909 Get to High Ground and if 38912 has been accepted
Also, Quest 38913 was listing 40515 as it's next quest for some reason, removed this link as well since it would cause issues. Likely many more in this zone need fixed. Most will have to wait for a large audit of phasing/scripting/quest order, but this is at least fixed.
