### ISSUE TITLE
[QUEST] throne-of-the-tides-azsharas-power

### ISSUE THREAD

**Issue by JRMISHA** [holydeew/WoWHellgarve-Legion#361]
When I killed the enemies I didn't complete it, nor did I save the panda, it bugged in the 2nd PHASE
https://www.wowhead.com/quest=40341/throne-of-the-tides-azsharas-power
ID: 40341

**Comment by skeezerbean** [comment]
A fix has been sent in with massive overhaul of the Shaman class hall. This should also be fixed. If you had talked to the giant before healing, then the Stage 1 was still active, and freeing the panda wouldn't properly register. This is now fixed, and won't be able to talk to the giant to continue until he's been healed up. Once the fix is applied, this should be working.
