### ISSUE TITLE
Dungeon Finder - Stuck in Queue

### ISSUE THREAD

**Issue by jdbhkf** [holydeew/WoWHellgarve-Legion#374]
After completing a dungeon, it is impossible to leave the queue. The only solution I've found is to log out and back in.

**Comment by skeezerbean** [comment]
Right click the queue icon after you enter and leave the queue before killing anything and you'll be good to go. Otherwise it can bug and a relog is the only fix. This is because of the bypassing to let single players hit dungeons from the menu without needing a full team, but it doesn't always behave well. This is how to work around it.
