### ISSUE TITLE
[Quest] Legacy of the Icebreaker (Warrior Protection Artifact Weapon Scenario)

### ISSUE THREAD

**Issue by Whooshy18** [holydeew/WoWHellgarve-Legion#385]
When trying to get the Protection Warrior Artifact Weapon the Scenario is undoable.
The Swirling Storms npc's at the entrance of the tomb don't dissapear after having been killed.
Hrunthnir keeps standing on them and when they are 'attackable' again he fights them.

During Stage 4 you're supposed to protect Hrunthnir, but as he keeps attacking those npc's at the doorway
the scenario can't be continued.

Pulling the Swirling Storms to the room of the next Stage does trigger the interaction between Hruthnir and Magnar,
but after having killed Magnar nothing happends.

WoWheadlink: https://www.wowhead.com/guide/legion/artifacts/earth-warder-protection-warrior
![WoWScrnShot_091623_163456](https://github.com/holydeew/WoWHellgarve-Legion/assets/145067092/a057feb5-fa51-4d8e-8c36-5b97885381be)

**Comment by skeezerbean** [comment]
This should now be fixed, but they should never disappear. These go inactive for a time and rebuild their health, then start moving around again. Stay away from them, or attack them all together so that they go inactive at the same time. They should pop back to their home position once they reset. This whole scenario has been rescripted and should be much better.
